### ISSUE TITLE
Linux

### ISSUE THREAD

**Issue by questor** [janbender/PositionBasedDynamics#1]
Hi, I've made the needed changes to compile it in linux, I can create a pull-request if you're interested. Two questions:
- it runs very slow on my computer, but that could also be because I have an extremly shitty gfx-card in the laptop and it falls back to software rendering. I guess the simulation should run in realtime, right?
- density constraints for fluids is currently not included as well as the unified solver (is it correct that for the unified solver it would be needed to fill models with particles and create the needed constraints, otherwise the simulation is available in cpu?)

**Comment by questor** [comment]
okay, first question was (of course): debug-build is SLOW! release-build is working fine and fast :)

**Comment by janbender** [comment]
Hi, 

yes, I'm interested in the Linux version. 

We need again a bit time for the density constraint since we also must implement a demo for this but it will come soon. 

Yes, for the unified solver you just need particle models and the corresponding constraints. Then you can solve all constraints in the same solver loop. 

Cheers, 

Jan

**Comment by mruegenberg** [comment]
Here are some changes that I did that are necessary (but possibly not sufficient) for non-Windows builds:

- I got CMake to go through on Linux by wrapping the set_target_properties calls in `extern/freeglut/src/CMakeLists.txt` and `PositionBasedDynamics/CMakeLists.txt` in a `IF(DEFINED IBDS_STATIC_LIBRARY_FLAGS_RELEASE) ... ENDIF()` block, which should probably be there anyway.

- adding `#include <cfloat>` at the top in `PositionBasedDynamics/PositionBasedDynamics.cpp`. It might be better to use `numeric_limits<float>`

- the freeglut version is broken, as it lacks the x11 subdir. Since most Linux users can install freeglut easily, it might be better to just use the one supplied by the OS when not on Windows

- unchecked_array_iterator is Windows-specific. I was able to just replace it with its argument (i.e the pointer it's wrapping)

- `__forceinline` is Windows-specific. Usually, it's probably best to leave this undefined and let the compiler figure things out. If this is really wanted, do the right thing for GCC:
    ~~~~
#ifdef _WIN32
#define FORCE_INLINE __forceinline
#else
#define FORCE_INLINE __attribute__((always_inline))
#endif
    ~~~~

- BarDemo and ClothDemo use a variable `bool pause`. Since there's also the function `pause()`, this is an error. => renamed to `doPause`

- IndexedFaceMesh.h uses code a la `for (auto i(0u); i < m_verticesFaces.size(); ++i)`. I get an error, probably because C++11 is not used. Either pass `-std=c++11` as an extra CFLAG or replace `auto` with `size_t`.

- `Demos/BarDemo/TetModel.cpp` and `Demos/ClothDemo/TriangleModel.cpp` use a backslash for an include. Everyone, including, afaik, Windows understands forward slashes.

- Demos/Visualization/MiniGL.cpp is missing an `#include <cstdio>` for `fprintf`

The only remaining problem is actually linking things, i.e I get
~~~~
Linking CXX executable ../../../bin/ClothDemo
/usr/bin/ld: cannot find -lfreeglut
/usr/bin/ld: cannot find -lopengl32.lib
/usr/bin/ld: cannot find -lglu32.lib
/usr/bin/ld: cannot find -lAntTweakBar.lib
~~~~

**Comment by mruegenberg** [comment]
I  went ahead and applied all my fixes as well as clean CMake linking. I can cionfirm slowness when doing  a debug build, so `cmake -DCMAKE_BUILD_TYPE=Release ..` makes more sense.

(See #2)

**Comment by questor** [comment]
thanks marcel, that's what I have done aswell :)    I have included freeglut and anttweakbar as sources because I don't like installing dev-libs local and dunno about incompatibilities with newer versions, but that's personal style...

**Comment by janbender** [comment]
Thanks for your Linux versions. I will test them after the Siggraph Asia deadline.

**Comment by janbender** [comment]
Thanks for your help. I added your changes and now it should work unter Linux.
