### ISSUE TITLE
Performance drop

### ISSUE THREAD

**Issue by SchneiderDaniel** [janbender/PositionBasedDynamics#16]
Hi everyone,

this morning I accidentally compiled a very old version (1.1.0) of the library. Afterwards I compiled the current version. (Both compiled with -DCMAKE_BUILD_TYPE=Release ).

I experience a noticeable performance drop between the two versions. E.g. the cloth demo is no longer performing in real time. I compared the code. The old one is single core (without OpenMP) and the current version is multi core (with OpenMP).

To me it is the same behavior I experienced when I programmed a CPU parallized PBD algorithm long long time ago. My experience was that it is not worth programming a parallized version of the PBD algorithm on the CPU because the overhead of OpenMP and the necessary data structures is too large and therefore the single core outperforms the multi core version. (GPU is a different story)

I'm not sure if my observation is correct or if I miss something. Any opinion on this topic?

Thanks in advance and best wishes from Stuttgart
Daniel

PS: I compiled under Linux Ubuntu 12.10 and g++ 4.8.1

**Comment by janbender** [comment]
Hi, 

the difference between version 1.1.0 and the current one is that in the current cloth demo a 50x50 grid is used and the default simulation method is FEM based PBD. In the older version only a 30x30 grid was simulated and the default method used distance constraints which is faster but less accurate. So I don't think that there is a performance drop since in the current version the simulation is far more complex. 

Jan

**Comment by SchneiderDaniel** [comment]
Hi,

thanks for that hint. That is something I missed. Nevertheless, I changed the grid size and the performance on the single core variant is still superior. I will look a bit deeper into it. Probably, I make something wrong.

Daniel
